import './plan.css';
import {createFlyCompanion} from './fly-companion.js';
import {createBrainActivity} from './brain-activity.js';
import {createMineScene} from './mine-scene.js';
const $=id=>document.getElementById(id);
let plan={bore_count:10,view_extent:10000,initial_head:-355,initial_floor:-350,floors:Array.from({length:10},(_,i)=>-375-8*i),rates:[[1570.984321878203, 0.0, 3186.867486077704, 3895.6821713371346, 0.0, 2217.332324335476, 0.0, 2897.318542588332, 3899.4218266317894, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [2769.7863630549673, 0.0, 1153.6632401637787, 739.8705219941891, 704.8282998867569, 2072.808789937238, 0.0, 1142.8098905903767, 921.0710286124403, 438.53493007916785], [611.2714449435892, 0.0, 767.8583359015217, 940.1884481044046, 0.0, 1239.3211372700216, 0.0, 824.9348856185379, 1045.6098476020773, 0.0], [0.0, 130.59104938535933, 1717.1296552770057, 680.0135074458746, 1221.738427871757, 0.0, 214.60063413934034, 1409.2753642915347, 669.4775870794012, 1328.2870125174172], [2824.9688697348024, 0.0, 955.4360601872521, 962.5759535618032, 0.0, 3002.1744887112563, 0.0, 1027.095222733873, 1116.6875750990584, 0.0], [0.0, 0.0, 1628.2361503022769, 742.8985669116918, 885.47771656398, 0.0, 47.12599796775411, 1455.86566888536, 709.268115278034, 936.2869496282441], [3505.648297134633, 0.0, 1283.263944654911, 1189.2160040298268, 0.0, 3566.8519350303504, 0.0, 1248.7128770858224, 1212.006615857355, 0.0], [0.0, 905.375434846486, 1182.9217779209343, 1135.5674199804691, 0.0, 0.0, 1026.047542351647, 1028.0471005046177, 1149.3536111898954, 0.0], [3478.8174320274557, 102.53629290627066, 1211.093616254468, 1495.9867233684886, 0.0, 3461.5681068612284, 366.7173181179302, 1165.190400378637, 1734.3417573563631, 0.0]],objective:'drawdown',conductivity:.05,thickness:200,storativity:.01,capacity:6000,active_year:0};
const flyCompanion=createFlyCompanion($('fly-companion'));
let brainActivity;try{brainActivity=createBrainActivity($('brain-window'));}catch{}
let checkpoint=null;let playback=null;
let canPause=false;let scene,busy=false,stop=false,session=null,last=null,history=[],benchmarkVolume=null;
try{scene=createMineScene($('mine-scene'));}catch(e){$('loading').textContent='3-D graphics unavailable. Numerical and learning controls still work.';}
const status=text=>$('activity').textContent=text;
function phase(value,text,learning=false){flyCompanion.setPhase(value,learning);brainActivity?.setPhase?.(value,learning);if(value!=='idle')brainActivity?.flash(value==='pulling'?'action':'sense');$('control-room').dataset.phase=value;scene?.setActivity(value,text);$('fly-status').textContent=value.toUpperCase();$('console-message').textContent=text;$('brain-window').dataset.phase=value;document.querySelectorAll('#brain-map circle').forEach(n=>n.classList.toggle('active',value==='typing'?(learning?['sense','values','update']:['sense','values']).includes(n.dataset.node):value==='pulling'?n.dataset.node==='action':false));}
function lock(value,pausable=canPause){busy=value;canPause=value&&pausable;document.querySelectorAll('input,select:not(#playback-speed),.setup button,#fit-target,#simulate,#train,#export,#restart-training').forEach(e=>e.disabled=value);$('pause').disabled=!canPause;document.querySelector('main').setAttribute('aria-busy',String(value));}
async function post(path,data){
 const portable=path.startsWith('/api/learn/');if(portable){const operation=path.split('/').at(-1);data=operation==='start'?{operation,request:data}:{operation,checkpoint};path='/api/portable/learn';}
 const abort=new AbortController(),started=Date.now(),progress=$('request-status');progress.hidden=false;
 const update=()=>{progress.textContent=`Calculating · ${Math.floor((Date.now()-started)/1000)} s · first use of aquifer settings can take longer${stop?' · pause requested':''}`;};update();
 const timer=setInterval(update,1000),timeout=setTimeout(()=>abort.abort(),180000);
 try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:abort.signal});const raw=await r.text();let body;
  try{body=JSON.parse(raw);}catch{throw Error(`The model server returned no usable result (HTTP ${r.status}). Please try again; your last successful result is retained.`);}
  if(!r.ok)throw Error(typeof body.detail==='string'?body.detail:`Model request failed (HTTP ${r.status}). Check the plan inputs and try again.`);
  if(portable){checkpoint=body.checkpoint;return body.value;}return body;
 }catch(e){if(e.name==='AbortError')throw Error('Calculation exceeded three minutes. Your previous result is retained. Try fewer bores or a shorter plan, then retry.');throw e;}
 finally{clearInterval(timer);clearTimeout(timeout);progress.hidden=true;}
}
function statistics(s,label){if(!s)return;$('stat-drawdown').textContent=`${s.max_drawdown_m.toFixed(2)} m`;$('stat-extent').textContent=s.extent_m===null?'—':`${s.extent_clipped||s.extent_underresolved?'≥ ':''}${(s.extent_m/1000).toFixed(2)} km`;$('stat-extent-note').textContent=s.extent_clipped?'Extends beyond modelled view; distance is a lower bound':s.extent_underresolved?'Narrow cone unresolved on grid; distance is a lower bound':'From pit centre · interpolated model grid estimate';$('stat-volume').textContent=Math.round(s.pumped_volume_m3).toLocaleString();$('stat-cost').textContent=`A$${Math.round(s.operating_cost_aud).toLocaleString()}`;$('stat-period').textContent=label;}
function invalidate(){brainActivity?.reset?.();flyCompanion.reset();$('restart-training').hidden=true;$('stat-period').textContent='Plan changed · statistics show the last evaluated plan until recalculated.';$('neural-updates').textContent='0000';$('neural-states').textContent='0 decisions learned';$('exploration-meter').value=0;$('exploration-value').textContent='—';playback=null;$('simulate').textContent='Run full simulation';if(last)$('graph-caption').textContent='Plan changed: graph shows the last evaluated design. Evaluate the plan to refresh.';session=null;checkpoint=null;$('train').textContent='Train fly';history=[];benchmarkVolume=null;$('benchmark-result').textContent='Plan changed; recalculate benchmark';$('learning-summary').textContent='Plan or strategy changed. Train a new policy.';$('episode-number').textContent='0';$('updates').textContent='0';$('epsilon').textContent='—';$('td-error').textContent='—';$('reward-chart').replaceChildren();$('action-values').textContent='No policy trained for the current plan.';}
function inputs(){plan.initial_head=Number($('initial-head').value);plan.view_extent=Number($('view-extent').value);plan.initial_floor=Number($('initial-floor').value);plan.objective=$('objective').value;plan.capacity=Number($('capacity').value);for(const id of ['conductivity','thickness','storativity'])plan[id]=Number($(id).value);}
function editors(){$('neural-actions').textContent=`${2*plan.bore_count*plan.floors.length+1} possible actions`;
 $('floor-rows').innerHTML=plan.floors.map((floor,i)=>`<tr><td>Y${i+1}</td><td><input aria-label="Year ${i+1} floor in metres AHD" data-floor="${i}" type="number" min="-600" max="-366" value="${floor}"></td><td>${floor-5}</td></tr>`).join('');
 $('floor-rows').querySelectorAll('input').forEach(el=>el.onchange=()=>{plan.floors[Number(el.dataset.floor)]=Number(el.value);el.closest('tr').lastElementChild.textContent=Number(el.value)-5;invalidate();status('Floor changed. Evaluate the updated plan.');});
 $('year-tabs').innerHTML=plan.floors.map((floor,i)=>`<button data-year="${i}" class="${i===plan.active_year?'selected':''}">YEAR ${i+1}<small>Edit rates</small></button>`).join('');
 $('year-tabs').querySelectorAll('button').forEach(el=>el.onclick=async()=>{if(busy)return;plan.active_year=Number(el.dataset.year);editors();if(last?.years[plan.active_year]){const y=last.years[plan.active_year];$('worst-head').textContent=y.worst_head.toFixed(2);$('target-label').textContent=`target ≤ ${y.target} m AHD`;$('total-rate').textContent=Math.round(y.total_rate).toLocaleString();$('active-bores').textContent=`${y.active_bores} / ${plan.bore_count}`;}});
 $('editing-year').textContent=`YEAR ${plan.active_year+1}`;
 $('bore-rows').innerHTML=plan.rates[plan.active_year].map((q,i)=>`<div class="bore-row" data-bore="${i}"><label for="bore-${i}">B${String(i+1).padStart(2,'0')}</label><input id="bore-${i}" type="number" min="0" max="${plan.capacity}" step="any" value="${q}" aria-label="Bore ${i+1} rate in cubic metres per day"></div>`).join('');
 $('bore-rows').querySelectorAll('input').forEach((el,i)=>el.onchange=()=>{plan.rates[plan.active_year][i]=Number(el.value);invalidate();status('Rate changed. Evaluate the updated plan.');});
}
function levelChart(r){if(r.axis){const edge=r.surface?[...r.surface[0],...r.surface.at(-1),...r.surface.flatMap(row=>[row[0],row.at(-1)])]:null;$('extent-label').textContent=`Modelled view ±${(r.axis.at(-1)/1000).toFixed(1)} km${edge?` · max edge drawdown ${Math.max(0,...edge.map(h=>r.initial_head-h)).toFixed(2)} m`:''} · display edge, not an aquifer boundary`; }
 const svg=$('level-chart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();
 const passed=r.timeline.filter(t=>t.head<=t.target+1e-5).length;$('target-meter').value=passed/r.timeline.length;$('target-value').textContent=`${passed}/${r.timeline.length} samples`;$('target-meter').setAttribute('aria-valuetext',`${passed} of ${r.timeline.length} received pit-target samples met`);
 const years=r.years,points=r.timeline.map(p=>({...p,time:p.day/365}));
 const vals=[...points.flatMap(p=>[p.head,p.floor,p.target]),...years.flatMap(p=>[p.floor,p.target]),r.initial_floor,r.initial_floor-5],lo=Math.floor((Math.min(...vals)-3)/5)*5,hi=Math.ceil((Math.max(...vals)+3)/5)*5;
 const x=t=>64+t/years.length*812,y=h=>195-(h-lo)/(hi-lo)*165;
 const add=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;svg.append(e);return e;};
 add('title',{},'Highest modelled pit head compared with annual bench progression and the five metre clearance target');
 for(let i=0;i<=4;i++){const h=lo+(hi-lo)*i/4;add('line',{x1:64,x2:876,y1:y(h),y2:y(h),stroke:'#d5d8c9'});add('text',{x:55,y:y(h)+4,'text-anchor':'end',fill:'#556b5a','font-size':11},h.toFixed(1));}
 add('text',{x:8,y:14,fill:'#556b5a','font-size':10},'m AHD');
 for(let i=0;i<=years.length;i++)add('text',{x:x(i),y:219,'text-anchor':'middle',fill:'#556b5a','font-size':11},`${i} yr`);
 for(const [key,color,dash]of [['floor','#775c45',''],['target','#a65036','6 4']]){
  const path=`M${x(0)},${y(r.initial_floor-(key==='target'?5:0))} `+years.map((v,i)=>`H${x(i+1)}V${y(v[key])}`).join(' ');
  add('path',{d:path,fill:'none',stroke:color,'stroke-width':2,'stroke-dasharray':dash,'data-series':key});
 }
 add('polyline',{points:points.map(p=>`${x(p.time)},${y(p.head)}`).join(' '),fill:'none',stroke:'#187c87','stroke-width':2.5,'data-series':'head'});
 for(const p of points){const dot=add('circle',{cx:x(p.time),cy:y(p.head),r:4,fill:p.head>p.target+1e-5?'#ba5839':'#187c87','data-head':p.head});const title=document.createElementNS(ns,'title');title.textContent=`Year ${p.time}: head ${p.head.toFixed(2)}, floor ${p.floor}, target ${p.target} m AHD`;dot.append(title);}
 $('level-values').innerHTML=points.map(p=>`<tr><td>${p.time}</td><td>${p.head.toFixed(2)}</td><td>${p.floor}</td><td>${p.target}</td></tr>`).join('');
 $('level-compliance').textContent=!r.confined_valid?'Outside model assumptions':r.feasible?'All sampled targets met':'Target exceedance';
 $('graph-caption').textContent='Highest modelled head across 25 pit controls · monthly samples from day 0 · orange points exceed target. Floor holds level, then steps down at each year-end date; the target follows 5 m below. Head lines are guides.';
}

function display(r){brainActivity?.setModel?.(r);statistics(r.statistics,`Full ${r.duration_days/365}-year plan · peak drawdown and reach across monthly samples. Minimise impacts while meeting the mine-plan target.`);playback=null;$('simulate').textContent='Run full simulation';levelChart(r);$('objective-summary').textContent=`${r.objective} score: ${r.score.toFixed(3)} · synthetic operating cost A$${Math.round(r.operating_cost_aud).toLocaleString()} · K ${r.conductivity} m/day · T ${r.transmissivity} m²/day`;last=r;plan.rates=r.rates.map(q=>[...q]);plan.active_year=Math.min(plan.active_year,r.years.length-1);editors();if(busy)lock(true);const year=r.years[plan.active_year];$('worst-head').textContent=year.worst_head.toFixed(2);$('target-label').textContent=`target ≤ ${year.target} m AHD`;$('total-rate').textContent=Math.round(year.total_rate).toLocaleString();$('plan-volume').textContent=(r.total_volume/1e6).toFixed(3);$('active-bores').textContent=`${year.active_bores} / ${plan.bore_count}`;$('feasibility').textContent=!r.confined_valid?'Outside confined assumption':r.feasible?'ALL YEARS PASS':'TARGET NOT MET';$('feasibility').style.color=r.feasible&&r.confined_valid?'#b9e5bc':'#e5b080';$('mine-year').textContent='FULL PLAN PREVIEW';$('mesh-label').textContent=`Day ${r.duration_days} / run simulation to watch progression`;
 const max=Math.max(...r.years.map(y=>y.total_rate),1);$('annual-bars').innerHTML=r.years.map(y=>`<div class="annual-row ${y.feasible?'':'failed'}"><span>Y${y.year}</span><div class="bar-track"><div class="bar-fill" style="width:${y.total_rate/max*100}%"></div></div><strong>${Math.round(y.total_rate).toLocaleString()} m³/d · ${y.active_bores}B</strong></div>`).join('');scene?.update(r);if(scene)$('loading').hidden=true;
}
async function evaluate(reset=true){if(busy||!validForm()||!planReady())return;inputs();if(reset)invalidate();lock(true);phase('typing','Evaluating the transient mine plan…');status('Python is evaluating pumping history and monthly pit controls.');try{display(await post('/api/plan/evaluate',plan));status('Plan evaluated. Select a teaching strategy, then train the fly.');phase('idle','Model evaluated. Ready for training.');return true;}catch(e){status(e.message);phase('idle','Model unavailable. No new result.');return false;}finally{lock(false);}}
function planReady(){if(Number($('bore-count').value)!==plan.bore_count||Number($('year-count').value)!==plan.floors.length){status('Apply the new bore and year counts with Create / resize mine plan first.');return false;}return true;}
function validForm(){for(const el of document.querySelectorAll('input'))if(!el.checkValidity()){for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;el.reportValidity();return false;}return true;}
$('create-plan').onclick=async()=>{if(busy||!validForm())return;const n=Number($('bore-count').value),years=Number($('year-count').value),q=Number($('initial-rate').value);if(q>Number($('capacity').value)){status('Initial rate must not exceed bore capacity.');return;}plan.rates=Array.from({length:years},(_,y)=>Array.from({length:n},(_,i)=>plan.rates[y]?.[i]??q));plan.floors=Array.from({length:years},(_,i)=>plan.floors[i]??Math.max(-600,plan.floors.at(-1)-8*(i-plan.floors.length+1)));plan.bore_count=n;plan.active_year=Math.min(plan.active_year,years-1);inputs();invalidate();editors();return evaluate(false);};
$('all-off').onclick=()=>{if(busy||!planReady())return;plan.rates[plan.active_year].fill(0);invalidate();editors();return evaluate(false);};$('equalise').onclick=()=>{if(busy||!planReady())return;const q=plan.rates[plan.active_year],average=q.reduce((a,b)=>a+b,0)/q.length;q.fill(average);invalidate();editors();return evaluate(false);};
$('evaluate').onclick=()=>{if(validForm())return evaluate();};
for(const id of ['initial-head','view-extent','initial-floor','objective','capacity','conductivity','thickness','storativity','teaching-strategy','rate-step','guidance','max-moves'])$(id).addEventListener('change',()=>{inputs();invalidate();});
$('guidance').oninput=()=>{$('guidance-value').textContent=$('guidance').value+'%';};
$('fit-target').onclick=async()=>{
 if(busy||!validForm()||!planReady())return;inputs();lock(true);stop=false;phase('typing','Fitting pumping to the entire target schedule…');status('Fitting the complete mine plan. The result will appear when the calculation finishes.');
 try{const r=await post('/api/plan/benchmark',{...plan,objective:'drawdown'});if(!r.success){status(r.message);return;}
  plan.objective='drawdown';$('objective').value='drawdown';invalidate();display(r.result);status('Target-fit pumping applied. Run the full simulation to inspect clearance. This is a conventional solution, not an RL result.');
 }catch(e){status(e.message);}finally{phase('idle','Target-fit calculation finished.');lock(false);}
};

$('benchmark').onclick=async()=>{if(busy||!validForm()||!planReady())return;inputs();lock(true);phase('typing','Solving the conventional benchmark…');status('Calculating the benchmark for comparison…');try{const r=await post('/api/plan/benchmark?preview=false',plan);if(r.success){benchmarkVolume=r.result.total_volume;$('benchmark-result').textContent=`LP ${r.result.objective}: ${(benchmarkVolume/1e6).toFixed(3)} million m³`;status('Benchmark calculated for comparison. Your pumping inputs remain available for training.');}else status(r.message);}catch(e){status(e.message);}finally{phase('idle','Benchmark complete.');lock(false);}};
function chart(records){const svg=$('reward-chart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();if(!records.length)return;const lo=Math.min(0,...records.map(r=>r.reward)),hi=Math.max(1,...records.map(r=>r.reward));const points=records.map((r,i)=>`${15+i*290/Math.max(1,records.length-1)},${85-(r.reward-lo)/(hi-lo)*65}`);const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#bee2ae');line.setAttribute('stroke-width','2');svg.append(line);for(const [text,y] of [[hi.toFixed(1),12],[lo.toFixed(1),96]]){const t=document.createElementNS(ns,'text');t.setAttribute('x','5');t.setAttribute('y',y);t.setAttribute('fill','#92b0a0');t.setAttribute('font-size','9');t.textContent=text;svg.append(t);}}
function metrics(r){const m=r.metrics;brainActivity?.update?.(m,{bores:plan.bore_count,years:plan.floors.length});flyCompanion.reward(m.reward);brainActivity?.flash('update',1+Math.min(m.td_error,1));$('neural-updates').textContent=String(m.updates).padStart(4,'0');$('neural-states').textContent=`${m.updates} decisions · ${m.parameters} learned weights`;$('exploration-meter').value=m.epsilon;$('exploration-value').textContent=`${Math.round(m.epsilon*100)}%`;$('brain-window').classList.remove('updated');void $('brain-window').offsetWidth;$('brain-window').classList.add('updated');history=r.history;$('episode-number').textContent=m.episode;$('epsilon').textContent=m.epsilon.toFixed(3);$('updates').textContent=m.updates;$('td-error').textContent=m.td_error.toFixed(4);chart(history);const recent=history.slice(-10),success=recent.filter(x=>x.success).length;$('learning-summary').textContent=`${success}/${recent.length} recent training episodes meet all monthly targets. ${m.parameters} shared learned weights. Best plan: ${m.best_success?"targets met":"not yet feasible"}, score ${m.best_score.toFixed(4)}. Last experiment score ${m.experiment_score.toFixed(4)}; reward ${m.reward.toFixed(2)}. Training includes teacher guidance. Continue training to keep improving the saved plan.`;}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
$('uniform-start').onclick=async()=>{if(busy||!validForm()||!planReady())return;inputs();plan.rates=plan.floors.map(()=>Array(plan.bore_count).fill(Math.min(plan.capacity,Math.max(0,Number($('initial-rate').value)))));await evaluate();};
$('train').onclick=async()=>{if(busy)return;if(!validForm()||!planReady()){$('learning-summary').textContent=`Training not started: ${$('activity').textContent}`;return;}inputs();lock(true,true);stop=false;$('restart-training').hidden=true;$('learning-summary').textContent=session?'Continuing the saved policy…':'Checking whether the mine plan can be achieved…';let trainingError=null;status('Checking plan feasibility before training…');const trainingPlan=structuredClone(plan);phase('typing','Initialising Q-learning from your strategy…');try{
 if(!session){const check=await post('/api/plan/benchmark?preview=false',trainingPlan);if(!check.success)throw Error('No feasible pumping schedule exists for these monthly targets, bore capacities and confined-aquifer assumptions. Adjust the mine plan or borefield before training.');benchmarkVolume=check.result.total_volume;$('benchmark-result').textContent=`LP ${check.result.objective}: score ${check.result.score.toFixed(4)} · ${(benchmarkVolume/1e6).toFixed(3)} million m³`;$('learning-summary').textContent='Feasibility checked. Validating starting pumping rates…';const start=await post('/api/learn/start',{plan:trainingPlan,strategy:$('teaching-strategy').value,step:Number($('rate-step').value),guidance:Number($('guidance').value)/100,max_moves:Number($('max-moves').value),seed:42});session=start.session;history=[];$('learning-summary').textContent='Training started. The first episode is calculating; reward statistics appear when it completes.';}
 const episodes=Number($('episodes').value),continuous=$('continuous-training').checked;
 for(let i=0;(continuous||i<episodes)&&!stop;i++){phase('typing',`Episode ${i+1}: observe → choose → reward → Q update`,true);status(`Training episode ${history.length?history.at(-1).episode+1:1} · ${continuous?"until paused":`${i+1}/${episodes} this batch`}. Real timflow responses; ε-greedy exploration.`);const r=await post('/api/learn/episode',{session});metrics(r);const state=await post('/api/plan/evaluate',{...trainingPlan,rates:r.rates,active_year:plan.active_year});display(state);$('level-compliance').textContent='Best training plan · '+$('level-compliance').textContent;phase('idle',`Episode ${r.metrics.episode}: ${r.metrics.moves} trials, reward ${r.metrics.reward.toFixed(2)}`);$('action-values').textContent=`Last training state ${r.metrics.last_state} / action ${r.metrics.last_action} / reward ${r.metrics.last_reward.toFixed(3)}`;await wait(220);}
 status(stop?'Training paused. Your learning progress and best plan are saved for this session.':'Training complete. Showing the best plan found. Continue training to keep learning.');
 }catch(e){trainingError=e.message;status(trainingError);$('learning-summary').textContent=`Training ${session?'interrupted':'not started'}: ${trainingError}`;$('restart-training').hidden=!!session||!trainingError.includes('Starting pumping rates lower sampled head below the confined aquifer roof');}finally{phase('idle',trainingError?'Training needs attention. See the learning panel.':stop?'Training paused.':'Training complete.');if(session)$('train').textContent='Continue training ↗';lock(false);}};
$('restart-training').onclick=async()=>{if(busy||!validForm()||!planReady())return;inputs();plan.rates=plan.floors.map(()=>Array(plan.bore_count).fill(0));invalidate();editors();if(await evaluate(false))await $('train').onclick();};
async function runSimulation(){
 if(busy||!validForm()||!planReady())return;
 inputs();if(!playback||playback.done)playback={plan:structuredClone(plan),next:0,timeline:[],buffer:[],done:false,failed:false};
 lock(true,true);stop=false;phase('typing','Simulating the complete pumping history…');
 try{
  while(!stop&&!playback.done){
   if(!playback.buffer.length){
    status(`Computing model results from day ${(playback.next*365/12).toFixed(0)}. First run may compile Python kernels.`);
    const batch=await post('/api/plan/simulate',{plan:playback.plan,start:playback.next,count:playback.next===0?1:4});
    playback.meta=batch;playback.buffer=batch.frames;playback.next=batch.next;playback.end=batch.done;
   }
   while(playback.buffer.length&&!stop){
    const frame=playback.buffer.shift();playback.timeline.push({day:frame.day,head:frame.head,floor:frame.floor,target:frame.target});
    playback.failed ||= !frame.feasible||!frame.confined_valid;
    const r={...playback.meta,...frame,timeline:playback.timeline,feasible:!playback.failed};
    const s=frame.statistics,previous=playback.statistics;playback.statistics={...s,max_drawdown_m:Math.max(s.max_drawdown_m,previous?.max_drawdown_m??0),extent_m:Math.max(s.extent_m??0,previous?.extent_m??0),extent_clipped:s.extent_clipped||!!previous?.extent_clipped,extent_underresolved:s.extent_underresolved||!!previous?.extent_underresolved};statistics(playback.statistics,`Through day ${frame.day.toFixed(0)} of ${r.duration_days} · peak drawdown/reach so far; volume and cost accumulated to this day.`);
    levelChart(r);scene?.update(r);if(scene)$('loading').hidden=true;
    $('simulation-clock').textContent=`DAY ${frame.day.toFixed(0)} / ${r.duration_days}`;
    $('simulation-progress').max=r.duration_days;$('simulation-progress').value=frame.day;
    $('simulation-head').textContent=`Head ${frame.head.toFixed(1)} / target ${frame.target.toFixed(1)} m AHD`;
    $('mine-year').textContent=`DAY ${frame.day.toFixed(0)}`;$('mesh-label').textContent=`Head ${frame.head.toFixed(2)} m AHD · floor ${frame.floor.toFixed(2)} m AHD`;
    phase('typing',`Day ${frame.day.toFixed(0)}: ${frame.feasible?'target met':'target missed'}. Pumped ${(frame.volume_to_date/1e6).toFixed(2)} million m³.`);
    status(`Simulating one complete ${r.duration_days/365}-year plan. ${playback.failed?'One or more sampled targets or model limits failed.':'All samples so far pass.'}`);
    await wait(Number($('playback-speed').value));
   }
   if(!playback.buffer.length&&playback.end)playback.done=true;
  }
  $('simulate').textContent=playback.done?'Replay simulation':'Resume simulation';
  status(playback.done?`Full-plan simulation complete. ${playback.failed?'Target or model-validity failures occurred; revise or optimise the schedule.':'All monthly samples meet the target.'}`:'Simulation paused. Resume continues from the same point.');
 }catch(e){status(e.message);$('simulate').textContent='Resume simulation';}
 finally{phase('idle','Simulation stopped at the displayed day.');lock(false);}
}
$('simulate').onclick=runSimulation;

$('pause').onclick=()=>{if(!canPause)return;stop=true;$('pause').disabled=true;status('Pause requested. Finishing the current calculation and retaining its results…');};
$('export').onclick=async()=>{if(busy)return;lock(true);status('Preparing export…');try{const learning=session?await post('/api/learn/export',{session}):null;const blob=new Blob([JSON.stringify({plan,result:last,simulation:playback?{timeline:playback.timeline,complete:playback.done,statistics:playback.statistics}:null,learning,benchmark_volume:benchmarkVolume},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hydrofly-mine-plan.json';a.click();status('Export downloaded.');setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){status(e.message);}finally{lock(false);}};
$('world-view').onclick=()=>{const active=document.body.classList.toggle('world-mode');$('world-view').textContent=active?'Mine plan':'Expand';};
$('follow-fly').onclick=()=>scene?.focusFly();$('reset-camera').onclick=()=>{scene?.resetCamera();$('section-view').textContent='Section view';};
$('section-view').onclick=()=>{$('section-view').textContent=scene?.toggleSection()?'Orbit view':'Section view';};$('head-toggle').onclick=()=>{$('head-toggle').setAttribute('aria-pressed',String(scene?.toggleSurface()));};
if(!scene)for(const id of ['follow-fly','reset-camera','section-view','head-toggle']){$(id).disabled=true;$(id).title='Requires WebGL 3-D support';}
editors();await evaluate(false);
