import './plan.css';
import {createMineScene} from './mine-scene.js';
const $=id=>document.getElementById(id);
let plan={bore_count:10,floors:[-375,-382,-390],rates:Array.from({length:3},()=>Array(10).fill(500)),conductivity:.2,thickness:200,storativity:.001,capacity:6000,active_year:0};
let scene,busy=false,stop=false,session=null,last=null,history=[],benchmarkVolume=null;
try{scene=createMineScene($('mine-scene'));}catch(e){$('loading').textContent='3-D graphics unavailable. Numerical and learning controls still work.';}
const status=text=>$('activity').textContent=text;
function phase(value,text,learning=false){$('control-room').dataset.phase=value;scene?.setActivity(value,text);$('fly-status').textContent=value.toUpperCase();$('console-message').textContent=text;document.querySelectorAll('#brain-map circle').forEach(n=>n.classList.toggle('active',value==='typing'?(learning?['sense','values','update']:['sense','values']).includes(n.dataset.node):value==='pulling'?n.dataset.node==='action':false));}
function lock(value){busy=value;document.querySelectorAll('input,select,.planner button,#train,#run-learned,#export,#year-tabs button').forEach(e=>e.disabled=value);$('pause').disabled=!value;}
async function post(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw Error(typeof body.detail==='string'?body.detail:'Check the plan: floors must deepen, rates must fit capacity, and all input values must be valid.');return body;}
function invalidate(){session=null;history=[];benchmarkVolume=null;$('benchmark-result').textContent='Plan changed; recalculate benchmark';$('learning-summary').textContent='Plan or strategy changed. Train a new policy.';$('episode-number').textContent='0';$('updates').textContent='0';$('epsilon').textContent='—';$('td-error').textContent='—';$('reward-chart').replaceChildren();$('action-values').textContent='No policy trained for the current plan.';}
function inputs(){plan.capacity=Number($('capacity').value);for(const id of ['conductivity','thickness','storativity'])plan[id]=Number($(id).value);}
function editors(){
 $('floor-rows').innerHTML=plan.floors.map((floor,i)=>`<tr><td>Y${i+1}</td><td><input aria-label="Year ${i+1} floor in metres AHD" data-floor="${i}" type="number" min="-600" max="-366" value="${floor}"></td><td>${floor-5}</td></tr>`).join('');
 $('floor-rows').querySelectorAll('input').forEach(el=>el.onchange=()=>{plan.floors[Number(el.dataset.floor)]=Number(el.value);el.closest('tr').lastElementChild.textContent=Number(el.value)-5;invalidate();status('Floor changed. Evaluate the updated plan.');});
 $('year-tabs').innerHTML=plan.floors.map((floor,i)=>`<button data-year="${i}" class="${i===plan.active_year?'selected':''}">YEAR ${i+1}<small>FLOOR ${floor} m</small></button>`).join('');
 $('year-tabs').querySelectorAll('button').forEach(el=>el.onclick=async()=>{if(busy)return;plan.active_year=Number(el.dataset.year);editors();await evaluate(false);});
 $('editing-year').textContent=`YEAR ${plan.active_year+1}`;
 $('bore-rows').innerHTML=plan.rates[plan.active_year].map((q,i)=>`<div class="bore-row" data-bore="${i}"><label for="bore-${i}">B${String(i+1).padStart(2,'0')}</label><input id="bore-${i}" type="number" min="0" max="${plan.capacity}" step="25" value="${q}" aria-label="Bore ${i+1} rate in cubic metres per day"></div>`).join('');
 $('bore-rows').querySelectorAll('input').forEach((el,i)=>el.onchange=()=>{plan.rates[plan.active_year][i]=Number(el.value);invalidate();status('Rate changed. Evaluate the updated plan.');});
}
function display(r){last=r;plan.rates=r.rates.map(q=>[...q]);plan.active_year=r.active_year;editors();if(busy)lock(true);const year=r.years[r.active_year];$('worst-head').textContent=year.worst_head.toFixed(2);$('target-label').textContent=`target ≤ ${year.target} m AHD`;$('total-rate').textContent=Math.round(year.total_rate).toLocaleString();$('plan-volume').textContent=(r.total_volume/1e6).toFixed(3);$('active-bores').textContent=`${year.active_bores} / ${plan.bore_count}`;$('feasibility').textContent=!r.confined_valid?'Outside confined assumption':r.feasible?'ALL YEARS PASS':'TARGET NOT MET';$('feasibility').style.color=r.feasible&&r.confined_valid?'#b9e5bc':'#e5b080';$('mine-year').textContent=`YEAR ${r.active_year+1}`;$('mesh-label').textContent=`End of year ${r.active_year+1} / piezometric head`;
 const max=Math.max(...r.years.map(y=>y.total_rate),1);$('annual-bars').innerHTML=r.years.map(y=>`<div class="annual-row ${y.feasible?'':'failed'}"><span>Y${y.year}</span><div class="bar-track"><div class="bar-fill" style="width:${y.total_rate/max*100}%"></div></div><strong>${Math.round(y.total_rate).toLocaleString()} m³/d · ${y.active_bores}B</strong></div>`).join('');scene?.update(r);if(scene)$('loading').hidden=true;
}
async function evaluate(reset=true){if(busy)return;inputs();if(reset)invalidate();lock(true);phase('typing','Evaluating the transient mine plan…');status('Python is evaluating pumping history and quarterly pit controls.');try{display(await post('/api/plan/evaluate',plan));status('Plan evaluated. Select a teaching strategy, then train the fly.');phase('idle','Model evaluated. Ready for training.');}catch(e){status(e.message);phase('idle','Model unavailable. No new result.');}finally{lock(false);}}
function validForm(){for(const el of document.querySelectorAll('input'))if(!el.checkValidity()){el.reportValidity();return false;}return true;}
$('create-plan').onclick=()=>{if(!validForm())return;const n=Number($('bore-count').value),years=Number($('year-count').value),q=Number($('initial-rate').value);if(q>Number($('capacity').value)){status('Initial rate must not exceed bore capacity.');return;}plan.rates=Array.from({length:years},(_,y)=>Array.from({length:n},(_,i)=>plan.rates[y]?.[i]??q));plan.floors=Array.from({length:years},(_,i)=>plan.floors[i]??Math.max(-600,plan.floors.at(-1)-8*(i-plan.floors.length+1)));plan.bore_count=n;plan.active_year=Math.min(plan.active_year,years-1);inputs();invalidate();editors();evaluate(false);};
$('all-off').onclick=()=>{plan.rates[plan.active_year].fill(0);invalidate();editors();evaluate(false);};$('equalise').onclick=()=>{const q=plan.rates[plan.active_year],average=q.reduce((a,b)=>a+b,0)/q.length;q.fill(average);invalidate();editors();evaluate(false);};
$('evaluate').onclick=()=>{if(validForm())evaluate();};
for(const id of ['capacity','conductivity','thickness','storativity','teaching-strategy','rate-step','guidance'])$(id).addEventListener('change',()=>{inputs();invalidate();});
$('guidance').oninput=()=>{$('guidance-value').textContent=$('guidance').value+'%';};
$('benchmark').onclick=async()=>{if(busy||!validForm())return;inputs();lock(true);phase('typing','Solving the conventional benchmark…');try{const r=await post('/api/plan/benchmark',plan);if(r.success){benchmarkVolume=r.result.total_volume;$('benchmark-result').textContent=`LP: ${(benchmarkVolume/1e6).toFixed(3)} million m³`;status('Benchmark calculated for comparison. Your pumping inputs remain available for training.');}else status(r.message);}catch(e){status(e.message);}finally{phase('idle','Benchmark complete.');lock(false);}};
function chart(records){const svg=$('reward-chart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();if(!records.length)return;const lo=Math.min(0,...records.map(r=>r.reward)),hi=Math.max(1,...records.map(r=>r.reward));const points=records.map((r,i)=>`${15+i*290/Math.max(1,records.length-1)},${85-(r.reward-lo)/(hi-lo)*65}`);const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#bee2ae');line.setAttribute('stroke-width','2');svg.append(line);for(const [text,y] of [[hi.toFixed(1),12],[lo.toFixed(1),96]]){const t=document.createElementNS(ns,'text');t.setAttribute('x','5');t.setAttribute('y',y);t.setAttribute('fill','#92b0a0');t.setAttribute('font-size','9');t.textContent=text;svg.append(t);}}
function metrics(r){const m=r.metrics;history=r.history;$('episode-number').textContent=m.episode;$('epsilon').textContent=m.epsilon.toFixed(3);$('updates').textContent=m.updates;$('td-error').textContent=m.td_error.toFixed(4);chart(history);const recent=history.slice(-10),success=recent.filter(x=>x.success).length;$('learning-summary').textContent=`${success}/${recent.length} recent training episodes meet all quarterly targets. ${m.states} learned states. Last reward ${m.reward.toFixed(2)}. Training includes teacher guidance; run the learned policy to test it alone.`;}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
$('train').onclick=async()=>{if(busy||!validForm())return;inputs();lock(true);stop=false;const trainingPlan=structuredClone(plan);phase('typing','Initialising Q-learning from your strategy…');try{
 const start=await post('/api/learn/start',{plan:trainingPlan,strategy:$('teaching-strategy').value,step:Number($('rate-step').value),guidance:Number($('guidance').value)/100,seed:42});session=start.session;history=[];
 const episodes=Number($('episodes').value);
 for(let i=0;i<episodes&&!stop;i++){phase('typing',`Episode ${i+1}: observe → choose → reward → Q update`,true);status(`Training episode ${i+1}/${episodes}. Real timflow responses; ε-greedy exploration.`);const r=await post('/api/learn/episode',{session});metrics(r);const state=await post('/api/plan/evaluate',{...trainingPlan,rates:r.rates,active_year:plan.active_year});display(state);phase('idle',`Episode ${r.metrics.episode}: ${r.metrics.moves} trials, reward ${r.metrics.reward.toFixed(2)}`);$('action-values').textContent=`Last training state ${r.metrics.last_state} / action ${r.metrics.last_action} / reward ${r.metrics.last_reward.toFixed(3)}`;await wait(220);}
 status(stop?'Training paused after the current episode. The learned policy is available.':'Training complete. Run the learned policy to test it without teacher guidance.');
 }catch(e){status(e.message);}finally{phase('idle','Policy ready if training completed.');lock(false);}};
$('run-learned').onclick=async()=>{if(busy)return;if(!session){status('Train the fly for this plan first.');return;}lock(true);stop=false;try{display(await post('/api/learn/run',{session}));for(let i=0;i<81&&!stop;i++){phase('typing','Reading the learned action values…');const d=await post('/api/learn/decide',{session});const n=plan.bore_count*plan.floors.length;const actions=d.q_values.map((value,i)=>({value,i})).sort((a,b)=>b.value-a.value).slice(0,4);$('action-values').textContent=`State ${d.state}\n`+actions.map(a=>`${a.i===2*n?'STOP':`Y${Math.floor((a.i%n)/plan.bore_count)+1} B${a.i%n%plan.bore_count+1} ${a.i<n?'＋':'−'}`} : ${a.value.toFixed(4)}`).join('\n');$('action-values').style.whiteSpace='pre-line';if(d.done){status(`${d.reason} ${last.feasible?'Quarterly targets met.':'Quarterly targets are NOT met.'}`);break;}
 phase('pulling',`Y${d.year+1} / B${d.well+1}: ${d.from_rate} → ${d.to_rate} m³/day`);const arrived=scene?await scene.operate(`Y${d.year+1} B${d.well+1}: ${d.to_rate} m³/day`,()=>stop):await wait(850).then(()=>!stop);if(!arrived||stop)break;const r=await post('/api/learn/act',{session});if(r.done){status(r.reason);break;}display(r.result);$('bore-rows').querySelector(`[data-bore="${d.well}"]`)?.classList.add('selected');status(`Learned-policy move ${r.move}: Y${d.year+1}, bore ${d.well+1}. Reward ${r.reward.toFixed(3)}. Q-values are frozen during evaluation.`);}
 if(stop)status('Policy run paused at the displayed design. Run learned policy restarts the evaluation from its training baseline.');
 }catch(e){status(e.message);}finally{phase('idle','Evaluation finished. Check target compliance.');lock(false);}};
$('pause').onclick=()=>{stop=true;status('Stopping after the current calculation; no further lever action will be started.');};
$('export').onclick=async()=>{try{const learning=session?await post('/api/learn/export',{session}):null;const blob=new Blob([JSON.stringify({plan,result:last,learning,benchmark_volume:benchmarkVolume},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hydrofly-mine-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){status(e.message);}};
$('world-view').onclick=()=>{const active=document.body.classList.toggle('world-mode');$('world-view').textContent=active?'Mine plan':'Explore world';};
$('follow-fly').onclick=()=>scene?.focusFly();$('reset-camera').onclick=()=>scene?.resetCamera();
$('section-view').onclick=()=>{$('section-view').textContent=scene?.toggleSection()?'Orbit view':'Section view';};$('head-toggle').onclick=()=>{$('head-toggle').setAttribute('aria-pressed',String(scene?.toggleSurface()));};
editors();await evaluate(false);
